Workaround for clazz sometimes being a weird hash
NoMethodError: undefined method `ancestors' for #<Hash:0x007fa8a0b44268>

Conflicts:
	lib/cequel/record/tasks.rb